<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AssemblyName>GnosiaArchipelagoRandomizer</AssemblyName>
        <Description>Archipelago Randomizer implementation for the SinglePlayer social deduction game Gnosia</Description>
        <Version>0.1.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <!--<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>-->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <RootNamespace>GnosiaArchipelagoRandomizer</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>D:\SteamLibrary\steamapps\common\GNOSIA\BepInEx\plugins\$(AssemblyName)</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\$(AssemblyName)</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
    </PropertyGroup>

    <Target Name="ZipMod" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <ZipDirectory SourceDirectory="bin\Release\$(AssemblyName)" DestinationFile="bin\Release\$(AssemblyName)-$(Version).zip" Overwrite="true" />
    </Target>

    <ItemGroup>
        <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
        <PackageReference Include="Archipelago.MultiClient.Net.Analyzers" Version="2.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="UnityEngine.Modules" Version="2019.4.17" IncludeAssets="compile" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>D:\SteamLibrary\steamapps\common\GNOSIA\Gnosia_Data\Managed\Assembly-CSharp.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>D:\SteamLibrary\steamapps\common\GNOSIA\Gnosia_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Rewired_Core">
        <HintPath>D:\SteamLibrary\steamapps\common\GNOSIA\Gnosia_Data\Managed\Rewired_Core.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Rewired_Windows">
        <HintPath>D:\SteamLibrary\steamapps\common\GNOSIA\Gnosia_Data\Managed\Rewired_Windows.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>D:\SteamLibrary\steamapps\common\GNOSIA\Gnosia_Data\Managed\Unity.TextMeshPro.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>D:\SteamLibrary\steamapps\common\GNOSIA\Gnosia_Data\Managed\UnityEngine.UI.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>

</Project>
