using System.Collections.Generic;
using gnosia;
using GnosiaArchipelagoRandomizer.Archipelago;
using HarmonyLib;
using UnityEngine;
using util;

namespace GnosiaArchipelagoRandomizer.Patches.Optional
{
    [HarmonyPatch(typeof(SearchScenario), "Initialize")]
    class EventSearchInitializePatch
    {
        static bool Prefix(SearchScenario __instance)
        {
            //Get gd
            gnosia.GameData gd = GameObject.Find("Application/GameLogManager/SaveDataManager").GetComponent<gnosia.GameData>();
            HashSet<long> checkedLocations = ArchipelagoClient.ServerData.CheckedLocations;
            //Base stuff (Modified)
            __instance.sc.Add(new SearchScenario.SearchContents(0, (gnosia.GameData gd) => false, (gnosia.GameData gd) => true, 1U, 0U, new List<int>(), new List<int>(), 0.01f, 9, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(36, (gnosia.GameData gd) => (checkedLocations.Contains(602)), (gnosia.GameData gd) => gd.baseData.loop < 40 && (gd.baseData.loop < 25 || gd.baseData.takashiAbil[3] / 50f < 0.29f), 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 1f, 9, 3, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(60, (gnosia.GameData gd) => (checkedLocations.Contains(603) && checkedLocations.Contains(10)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[6] & 2UL) > 0UL || gd.baseData.loop >= 40 || (gd.baseData.loop >= 25 && gd.baseData.takashiAbil[3] / 50f > 0.29f), 383U, 128U, new List<int> { 1 }, new List<int>(), 3f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(62, (gnosia.GameData gd) => (checkedLocations.Contains(605)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[0] & 512UL) > 0UL, 449U, 62U, new List<int> { 1 }, new List<int>(), 1f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(41, (gnosia.GameData gd) => (checkedLocations.Contains(802)), (gnosia.GameData gd) => true, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 0.5f, 7, 1, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(75, (gnosia.GameData gd) => (checkedLocations.Contains(804)), (gnosia.GameData gd) => true, 449U, 62U, new List<int> { 1, 6 }, new List<int>(), 1f, 7, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(76, (gnosia.GameData gd) => (checkedLocations.Contains(805)), (gnosia.GameData gd) => true, 449U, 62U, new List<int> { 1 }, new List<int>(), 1f, 9, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(78, (gnosia.GameData gd) => (checkedLocations.Contains(806)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[8] & 16UL) > 0UL && (gd.baseData.s_chara_all_flg[11] & 2UL) > 0UL && (gd.baseData.s_chara_all_flg[13] & 4UL) > 0UL, 449U, 62U, new List<int> { 1 }, new List<int>(), 1f, 15, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(79, (gnosia.GameData gd) => (checkedLocations.Contains(807)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[8] & 8UL) > 0UL && (gd.baseData.s_chara_all_flg[8] & 16UL) > 0UL && gd.baseData.loop >= 60, 383U, 128U, new List<int> { 1 }, new List<int> { 8 }, 2f, 13, 3, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(53, (gnosia.GameData gd) => (checkedLocations.Contains(102)), (gnosia.GameData gd) => true, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 1f, 7, 1, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(80, (gnosia.GameData gd) => (checkedLocations.Contains(103)), (gnosia.GameData gd) => true, 129U, 0U, new List<int> { 1 }, new List<int>(), 1f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(81, (gnosia.GameData gd) => (checkedLocations.Contains(104)), (gnosia.GameData gd) => Util.Count16((ushort)(gd.baseData.s_chara_all_flg[1] & 255UL)) >= 4, 383U, 128U, new List<int> { 1, 2, 3 }, new List<int>(), 1f, 15, 3, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(83, (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 549755813888UL) > 0UL, (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[1] & 4UL) > 0UL, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 2f, 11, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(45, (gnosia.GameData gd) => (checkedLocations.Contains(1002)), (gnosia.GameData gd) => gd.baseData.loop < 35, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 1f, 9, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(111, (gnosia.GameData gd) => (checkedLocations.Contains(1004)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[10] & 4UL) > 0UL && ((gd.baseData.s_chara_all_flg[10] & 2UL) > 0UL || gd.baseData.loop >= 35), 449U, 62U, new List<int> { 1 }, new List<int> { 4 }, 1f, 15, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(109, (gnosia.GameData gd) => (checkedLocations.Contains(1404)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[11] & 2UL) > 0UL && ((gd.baseData.s_chara_all_flg[14] & 4UL) > 0UL || (gd.baseData.s_chara_all_flg[2] & 2UL) > 0UL), 17U, 0U, new List<int> { 1, 4 }, new List<int>(), 2f, 15, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(114, (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 68719476736UL) > 0UL, (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[10] & 4UL) > 0UL && (gd.baseData.s_chara_all_flg[14] & 4UL) > 0UL && (gd.baseData.s_chara_all_flg[14] & 8UL) > 0UL, 449U, 2U, new List<int> { 1, 6 }, new List<int> { 8 }, 2f, 11, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(115, (gnosia.GameData gd) => (checkedLocations.Contains(1405)), (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 68719476736UL) > 0UL, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 1f, 13, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(99, (gnosia.GameData gd) => (checkedLocations.Contains(1206)), (gnosia.GameData gd) => gd.baseData.loop >= 40, 259U, 0U, new List<int> { 8 }, new List<int>(), 2f, 7, 1, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(67, (gnosia.GameData gd) => (checkedLocations.Contains(304)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 8589934592UL) > 0UL, 0U, 0U, new List<int> { 1, 6, 8 }, new List<int>(), 1f, 9, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(68, (gnosia.GameData gd) => (checkedLocations.Contains(305)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 8UL) > 0UL && (gd.baseData.s_chara_all_flg[3] & 4UL) > 0UL, 0U, 0U, new List<int> { 1, 2 }, new List<int>(), 1f, 15, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(118, (gnosia.GameData gd) => (checkedLocations.Contains(306)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 16UL) > 0UL && (gd.baseData.s_chara_all_flg[9] & 16UL) > 0UL, 449U, 8U, new List<int> { 1, 3 }, new List<int>(), 3f, 11, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(119, (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 17179869184UL) > 0UL, (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 32UL) > 0UL, 467U, 60U, new List<int> { 8 }, new List<int>(), 5f, 11, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(91, (gnosia.GameData gd) => (checkedLocations.Contains(702)), (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 1099511627776UL) > 0UL || gd.baseData.loop >= 80, 0U, 0U, new List<int> { 1, 8 }, new List<int>(), 1f, 13, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(92, (gnosia.GameData gd) => (checkedLocations.Contains(705)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[7] & 2UL) > 0UL && (gd.baseData.s_chara_all_flg[7] & 8UL) > 0UL, 449U, 62U, new List<int>(), new List<int> { 4 }, 1f, 15, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(102, (gnosia.GameData gd) => (checkedLocations.Contains(1102)), (gnosia.GameData gd) => true, 257U, 0U, new List<int> { 1 }, new List<int>(), 2f, 7, 1, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(127, (gnosia.GameData gd) => (checkedLocations.Contains(1106)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 32UL) > 0UL && (gd.baseData.sce_all_flg & 549755813888UL) > 0UL && (gd.baseData.sce_all_flg & 1073741824UL) > 0UL, 449U, 62U, new List<int>(), new List<int>(), 1f, 15, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(74, (gnosia.GameData gd) => (checkedLocations.Contains(1303)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[13] & 2UL) > 0UL, 383U, 128U, new List<int> { 1 }, new List<int>(), 1.5f, 13, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(73, (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 268435456UL) > 0UL, (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[11] & 2UL) > 0UL, 383U, 128U, new List<int>(), new List<int>(), 5f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(96, (gnosia.GameData gd) => (checkedLocations.Contains(505)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[9] & 4UL) > 0UL, 0U, 0U, new List<int> { 1, 2 }, new List<int>(), 1f, 11, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(54, (gnosia.GameData gd) => (checkedLocations.Contains(202)), (gnosia.GameData gd) => gd.baseData.loop < 30, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 1f, 9, 3, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(121, (gnosia.GameData gd) => (checkedLocations.Contains(204)), (gnosia.GameData gd) => true, 449U, 62U, new List<int>(), new List<int> { 8 }, 1f, 7, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(125, (gnosia.GameData gd) => (checkedLocations.Contains(205)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[2] & 8UL) > 0UL && (gd.baseData.s_chara_all_flg[2] & 4UL) > 0UL && (gd.baseData.sce_all_flg & 8589934592UL) > 0UL, 383U, 128U, new List<int>(), new List<int>(), 2f, 12, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(133, (gnosia.GameData gd) => (checkedLocations.Contains(202)), (gnosia.GameData gd) => gd.baseData.loop >= 25, 383U, 128U, new List<int> { 1 }, new List<int> { 8 }, 5f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(116, (gnosia.GameData gd) => (checkedLocations.Contains(402)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[5] & 32UL) > 0UL, 0U, 62U, new List<int> { 1 }, new List<int>(), 1f, 9, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(124, (gnosia.GameData gd) => (checkedLocations.Contains(405)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[4] & 2UL) > 0UL && (gd.baseData.s_chara_all_flg[4] & 4UL) > 0UL && (gd.baseData.s_chara_all_flg[4] & 8UL) > 0UL, 449U, 62U, new List<int> { 1 }, new List<int>(), 1f, 15, 3, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(87, (gnosia.GameData gd) => (checkedLocations.Contains(904)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[9] & 4UL) > 0UL && (gd.baseData.sce_all_flg & 268435456UL) > 0UL && gd.baseData.loop >= 40, 449U, 62U, new List<int> { 1, 8 }, new List<int>(), 3f, 15, 3, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(88, (gnosia.GameData gd) => (checkedLocations.Contains(905)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[9] & 8UL) > 0UL, 385U, 8U, new List<int> { 3 }, new List<int>(), 3f, 9, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(33, (gnosia.GameData gd) => (checkedLocations.Contains(302)), (gnosia.GameData gd) => true, 449U, 62U, new List<int> { 1 }, new List<int> { 8 }, 0.5f, 7, 1, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(49, (gnosia.GameData gd) => (checkedLocations.Contains(1202)), (gnosia.GameData gd) => true, 449U, 62U, new List<int> { 1 }, new List<int>(), 0.5f, 7, 1, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(98, (gnosia.GameData gd) => (checkedLocations.Contains(1204)), (gnosia.GameData gd) => true, 259U, 0U, new List<int> { 1, 8 }, new List<int>(), 1f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(66, (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 8589934592UL) > 0UL, (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[3] & 4294967296UL) > 0UL, 0U, 0U, new List<int> { 1, 3, 8 }, new List<int>(), 1f, 9, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(86, (gnosia.GameData gd) => (checkedLocations.Contains(902)), (gnosia.GameData gd) => ((gd.baseData.s_chara_all_flg[1] & 6UL) == 6UL && (gd.baseData.sce_all_flg & 2147483648UL) > 0UL) || (gd.baseData.loop >= 30 && ((gd.baseData.s_chara_all_flg[1] & 2UL) > 0UL || (gd.baseData.sce_all_flg & 2147483648UL) > 0UL)), 0U, 0U, new List<int>(), new List<int>(), 3f, 15, 3, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(63, (gnosia.GameData gd) => (checkedLocations.Contains(606)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[11] & 16UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 15, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(110, (gnosia.GameData gd) => (checkedLocations.Contains(1003)), (gnosia.GameData gd) => true, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 9, 1, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(113, (gnosia.GameData gd) => (checkedLocations.Contains(1007)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[14] & 16UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 13, 2, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(108, (gnosia.GameData gd) => (checkedLocations.Contains(1005)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[9] & 2UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 1f, 15, 3, 3));
            __instance.sc.Add(new SearchScenario.SearchContents(71, (gnosia.GameData gd) => (checkedLocations.Contains(1302)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[11] & 2UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 9, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(90, (gnosia.GameData gd) => (checkedLocations.Contains(704)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[7] & 4UL) > 0UL && (gd.baseData.s_chara_all_flg[9] & 8UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 1f, 11, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(95, (gnosia.GameData gd) => (checkedLocations.Contains(504)), (gnosia.GameData gd) => gd.baseData.loop >= 30, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 15, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(97, (gnosia.GameData gd) => (checkedLocations.Contains(506)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[4] & 4UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 9, 2, 4));
            __instance.sc.Add(new SearchScenario.SearchContents(122, (gnosia.GameData gd) => (checkedLocations.Contains(403)), (gnosia.GameData gd) => true, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 7, 1, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(94, (gnosia.GameData gd) => (checkedLocations.Contains(503)), (gnosia.GameData gd) => (gd.baseData.s_chara_all_flg[5] & 2UL) > 0UL, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 9, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(64, (gnosia.GameData gd) => (checkedLocations.Contains(303)), (gnosia.GameData gd) => true, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 7, 1, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(107, (gnosia.GameData gd) => (checkedLocations.Contains(1402)), (gnosia.GameData gd) => true, 0U, 0U, new List<int>(), new List<int>(), 0.5f, 11, 2, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(61, (gnosia.GameData gd) => (checkedLocations.Contains(604)), (gnosia.GameData gd) => true, 0U, 0U, new List<int>(), new List<int> { 4 }, 0.5f, 7, 1, 5));
            __instance.sc.Add(new SearchScenario.SearchContents(106, (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 34359738368UL) > 0UL, (gnosia.GameData gd) => (gd.baseData.sce_all_flg & 17179869184UL) > 0UL, 449U, 62U, new List<int>(), new List<int> { 8 }, 1f, 7, 1, 5));
            return false;
        }
    }
}
